

apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    environment: staging
    managed-by:  helm

apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    environment: production
    managed-by:  helm
